//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SoftUniEntities : DbContext
    {
        public SoftUniEntities()
            : base("name=SoftUniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Town> Towns { get; set; }
    
        public virtual ObjectResult<usp_findAllProjects_Result> usp_findAllProjects(string firsName, string lastName)
        {
            var firsNameParameter = firsName != null ?
                new ObjectParameter("firsName", firsName) :
                new ObjectParameter("firsName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_findAllProjects_Result>("usp_findAllProjects", firsNameParameter, lastNameParameter);
        }
    
        public virtual ObjectResult<usp_findAllProjectsN_Result> usp_findAllProjectsN(string firsName)
        {
            var firsNameParameter = firsName != null ?
                new ObjectParameter("firsName", firsName) :
                new ObjectParameter("firsName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_findAllProjectsN_Result>("usp_findAllProjectsN", firsNameParameter);
        }
    
        public virtual ObjectResult<usp_find_all_projects_Result> usp_find_all_projects(string firsName, string lastName)
        {
            var firsNameParameter = firsName != null ?
                new ObjectParameter("firsName", firsName) :
                new ObjectParameter("firsName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_find_all_projects_Result>("usp_find_all_projects", firsNameParameter, lastNameParameter);
        }

        public virtual ObjectResult<usp_find_projects_Result> FindProjects(string firsName, string lastName)
        {
            var firsNameParameter = firsName != null ?
                new ObjectParameter("firsName", firsName) :
                new ObjectParameter("firsName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("lastName", lastName) :
                new ObjectParameter("lastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_find_projects_Result>("usp_find_projects", firsNameParameter, lastNameParameter);
        }
    }
}
